"""Application-wide constants."""

APP_NAME = "Control-OFC"
APP_VERSION = "1.0.0"
ORG_NAME = "control-ofc"

# Daemon IPC
DEFAULT_SOCKET_PATH = "/run/control-ofc/control-ofc.sock"
API_TIMEOUT_S = 5.0

# Polling
POLL_INTERVAL_MS = 1000
LEASE_RENEW_INTERVAL_S = 30
CAPABILITIES_REFRESH_INTERVAL_S = 300

# Control loop
CONTROL_LOOP_INTERVAL_MS = 1000
HYSTERESIS_DEADBAND_C = 2.0
PWM_WRITE_THRESHOLD_PCT = 1

# History
HISTORY_DURATION_S = 7200  # 2 hours
HISTORY_MAX_SAMPLES = HISTORY_DURATION_S  # ~1 sample/sec

# Curves
DEFAULT_CURVE_POINTS = 5

# Pages
PAGE_DASHBOARD = 0
PAGE_CONTROLS = 1
PAGE_SETTINGS = 2
PAGE_DIAGNOSTICS = 3
