"""Markdown export of a PWM Test Report and of a comparison (DEC-404 Stage 5).

Written for a GitHub issue. Built from the same view models the app renders
(``view.build_report_view``, ``compare.compare_reports``), so the file says
exactly what the window says and no wording rule is written twice.

**Every dynamic string is escaped.** Labels, aliases, notes and daemon tokens
can hold Markdown or raw HTML (GitHub renders both), so :func:`md` backslash-
escapes every ASCII punctuation character — CommonMark allows any of them to be
escaped — and folds line breaks, which would otherwise end a table row or start
a heading. Nothing a user or a daemon wrote can become a link, an image, a tag
or structure.

S5-11: there is no length cap. A long report is meant to be **attached** to an
issue rather than pasted (GitHub accepts ``.md`` attachments; an issue body is
limited to 65,536 characters), and the file's first lines say so.
"""

from __future__ import annotations

import string
from collections.abc import Iterable, Mapping, Sequence

from control_ofc.services.pwm_report.compare import (
    CATEGORY_NOT_COMPARABLE,
    CATEGORY_ORDER,
    CATEGORY_TITLES,
    Comparison,
    Difference,
)
from control_ofc.services.pwm_report.view import FindingRow, ReportView, build_report_view

_PUNCT = frozenset(string.punctuation)

ATTACH_NOTE = (
    "Generated by Control-OFC. If this is long, attach the file to the issue rather "
    "than pasting it (an issue body holds at most 65,536 characters)."
)


def md(value: object) -> str:
    """Escape one dynamic string for Markdown: fold line breaks to spaces and
    backslash-escape every ASCII punctuation character."""
    text = " ".join(str(value).splitlines())
    return "".join("\\" + ch if ch in _PUNCT else ch for ch in text)


def _table(header: Sequence[str], rows: Iterable[Sequence[object]]) -> list[str]:
    out = ["| " + " | ".join(md(h) for h in header) + " |"]
    out.append("|" + "|".join(" --- " for _ in header) + "|")
    for row in rows:
        out.append("| " + " | ".join(md(v) for v in row) + " |")
    return out


def _findings(title: str, rows: Sequence[FindingRow]) -> list[str]:
    out = [f"## {md(title)} ({len(rows)})", ""]
    if not rows:
        out += ["Nothing here.", ""]
        return out
    for r in rows:
        scope = f" Scope: {md(r.scope)}." if r.scope else ""
        out.append(
            f"- **{md(r.result_label)}** — {md(r.statement)}{scope} "
            f"_Source: {md(r.provenance_label)}._"
        )
    out.append("")
    return out


def report_markdown(doc: Mapping) -> str:
    vm: ReportView = build_report_view(doc)
    out = [
        f"# {md(vm.title)} — {md(vm.report_id)}",
        "",
        f"> {md(ATTACH_NOTE)}",
        "",
        f"**State:** {md(vm.state_label)}  ",
        f"{md(vm.when_line)}",
        "",
    ]
    if vm.state_reason:
        out += [md(vm.state_reason), ""]
    out += [f"- {md(line)}" for line in vm.summary_lines]
    if vm.trace_note:
        out.append(f"- {md(vm.trace_note)}")
    out.append("")
    out += _findings("Needs attention", vm.attention)
    out += _findings("Observations", vm.observations)
    out += _findings("Restoration", vm.restoration)
    out += ["## Channels", ""]
    out += _table(
        ("Channel", "Stable id", "What it is", "Tests"),
        (
            (
                ch.name,
                ch.channel_id,
                ch.subtitle,
                "; ".join(f"{t.title}: {t.status_label}" for t in ch.tests) or "read-only",
            )
            for ch in vm.channels
        ),
    )
    out.append("")
    out += _findings("Not tested", vm.not_tested)
    out += ["## Environment", ""]
    out += _table(("", "Value"), vm.environment)
    out += ["", "## Configuration", ""]
    out += _table(("", "Value"), vm.configuration)
    out += ["", "## How to read this report", ""]
    out += _table(("Source", "Meaning"), vm.legend)
    out.append("")
    return "\n".join(out)


def _diff_rows(rows: Sequence[Difference]) -> list[str]:
    return _table(
        ("What", "Earlier", "Later", "Difference", "Note"),
        ((r.subject, r.earlier, r.later, r.delta, r.note) for r in rows),
    )


def comparison_markdown(cmp: Comparison) -> str:
    e, lt = cmp.earlier, cmp.later
    out = [
        "# PWM Test Report comparison",
        "",
        f"> {md(ATTACH_NOTE)}",
        "",
    ]
    out += _table(
        ("", "Earlier", "Later"),
        (
            ("Report", e.report_id, lt.report_id),
            ("Started (UTC)", e.started_at, lt.started_at),
            ("Machine", e.machine, lt.machine),
            ("State", e.state_label, lt.state_label),
            (
                "GUI / daemon",
                f"{e.gui_version} / {e.daemon_version}",
                f"{lt.gui_version} / {lt.daemon_version}",
            ),
        ),
    )
    out += [
        "",
        "Differences are later minus earlier. No difference is judged significant "
        "or not; each measured value is shown beside the spread its own run recorded.",
        "",
        "## Start conditions",
        "",
    ]
    out += _diff_rows(cmp.start_conditions)
    out += ["", "## Channels", ""]
    out.append(f"Paired by stable id: {len(cmp.paired)}.")
    for title, items in (
        ("Only in the earlier report", cmp.only_earlier),
        ("Only in the later report", cmp.only_later),
    ):
        if items:
            out += ["", f"**{md(title)}:**", ""]
            out += [f"- {md(name)} ({md(cid)})" for cid, name in items]
    if cmp.possible_renames:
        out += [
            "",
            "**Possibly renamed** (same chip, device and PWM index, different label — "
            "an inference; these are not compared):",
            "",
        ]
        out += [f"- {md(a)} → {md(b)}" for a, b in cmp.possible_renames]
    out.append("")
    for category in CATEGORY_ORDER:
        rows = cmp.in_category(category)
        same = cmp.same_counts.get(category, 0)
        out += [f"## {md(CATEGORY_TITLES[category])} ({len(rows)})", ""]
        if same and category != CATEGORY_NOT_COMPARABLE:
            out += [f"{same} other compared value(s) are the same in both reports.", ""]
        if rows:
            out += _diff_rows(rows)
        else:
            out.append("Nothing here.")
        out.append("")
    return "\n".join(out)
